# #############################
# # BUILD FOR LOCAL DEVELOPMENT
# #############################

FROM node:20.12.2 AS development

RUN npm install -g bun

WORKDIR /app

COPY package.json bun.lockb ./

COPY prisma ./prisma/

RUN bun install

RUN bun install @prisma/client

RUN bunx prisma generate

COPY . .

EXPOSE 3333

CMD [ "bun", "dev" ]
